import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { I18nProvider } from './i18n';
import '@fontsource-variable/onest';
import '@fontsource/cormorant/latin-500.css';
import '@fontsource/cormorant/latin-600.css';
import '@fontsource/cormorant/latin-700.css';
import '@fontsource/cormorant/latin-500-italic.css';
import '@fontsource/cormorant/cyrillic-500.css';
import '@fontsource/cormorant/cyrillic-600.css';
import '@fontsource/cormorant/cyrillic-700.css';
import '@fontsource/cormorant/cyrillic-500-italic.css';
import '@fontsource/cormorant/cyrillic-ext-500.css';
import '@fontsource/cormorant/cyrillic-ext-600.css';
import '@fontsource/cormorant/cyrillic-ext-700.css';
import '@fontsource/cormorant/cyrillic-ext-500-italic.css';
import './styles.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><I18nProvider><App /></I18nProvider></React.StrictMode>);
